config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show, :new, :create] do
    resources :tweets, only: [:index]
  end
end

app/models/tweet.rb
class Tweet
  attr_reader :text

  def initialize(text)
    @text = text
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :prepare_user

  def index
    @tweets = TweetService.new(@user.twitter_handle).all
  end

  private

  def prepare_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = RegisterUserService.new(user_params).register

    if @user
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :twitter_handle, :phone_number, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html

html
  head
    title TechLadies MVC Example

body
  = yield

app/views/tweets/index.html.slim
h1 #{@user.first_name}'s Tweets

table
  tbody

  - @tweets.each do |tweet|
    tr
      td #{tweet.text}

app/views/users/index.html.slim
h1 Users

table
  thead
    tr
      th Name
      th Actions

  tbody

  - @users.each do |user|
    tr
      td #{user.first_name}
      td #{link_to 'View', user_path(user)} - #{link_to 'Tweets', user_tweets_path(user)}

app/views/users/new.html.slim
h1 New user

= form_for @user do |f|
  div
    = f.label :first_name
    = f.text_field :first_name
  div
    = f.label :last_name
    = f.text_field :last_name
  div
    = f.label :twitter_handle
    = f.text_field :twitter_handle
  div
    = f.label :phone_number
    = f.text_field :phone_number
  div
    = f.label :email
    = f.text_field :email
  div
    = submit_tag 'Save'

app/views/users/show.html.slim
h1 User: #{@user.first_name} (#{@user.twitter_handle})

table
  tbody
    tr
      td E-mail:
      td #{@user.email}
    tr
      td Phone number:
      td #{@user.phone_number}